# Generated by Django 6.0.3 on 2026-03-24 09:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending_development', 'Pending development'), ('in_progress', 'In progress'), ('pending_review', 'Pending review'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=20)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('manager_notes', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2500)])),
                ('resolution_notes', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
